# @package _global_

module:
  _target_: emg2qwerty.lightning.HybridCTCModule
  in_features: 528
  mlp_features: [256, 256]
  
  # CNN Parameters
  block_channels: [32, 32, 32, 32]
  kernel_width: 32
  
  # RNN Parameters (2 layers instead of 3 now, prevent overfitting)
  rnn_hidden_size: 256
  rnn_num_layers: 2
  rnn_dropout: 0.3
  bidirectional: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
