# @package _global_

module:
  _target_: emg2qwerty.lightning.RNNCTCModule
  in_features: 528
  mlp_features: [256, 256]
  rnn_hidden_size: 256
  rnn_num_layers: 3
  rnn_dropout: 0.3
  bidirectional: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
