# @package _global_

module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528
  mlp_features: [256, 256]
  d_model: 256
  nhead: 8
  num_layers: 3
  dim_feedforward: 1024
  dropout: 0.2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
